spring:
  application:
    name: SzaunaWeb

  security:
    oauth2:
      client:
        registration:
          authsch:
            client-id: "YOUR_CLIENT_ID"
            client-secret: "YOUR_CLIENT_KEY"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - basic
              - displayName
              - mail
              - eduPersonEntitlement
        provider:
          authsch:
            authorization-uri: https://auth.sch.bme.hu/site/login
            token-uri: https://auth.sch.bme.hu/oauth2/token
            user-info-uri: https://auth.sch.bme.hu/api/profile
            user-name-attribute: internal_id

szaunaWeb:
  szaunaKorId: 435
  frontendUrl: TODO
  admins: "YOUR_INTERNAL_ID,INTERNAL_ID,INTERNAL_ID"
  jwt:
    secret: YOUR_SECRET_STRING
    experation: 3600000 #1 hour expiration
    issuer: Kir-Dev
    authTokenCookieName: auth_token